## Data Cleaning

##### Datasource: https://www.kaggle.com/datasets/yagunnersya/fifa-21-messy-raw-dataset-for-cleaning-exploring/data

### Goals:
#### Drop value & Formatting value so it is suitable for data analysis

### Import the libraries

In [1]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

### Import the data set

In [2]:
fifa = pd.read_csv('fifa21_raw_data.csv')

In [3]:
# data Overview
print(fifa.shape, '\n')
print(fifa.dtypes, '\n')
display(fifa.head())
display(fifa.info())

(18979, 77)

photoUrl       object
LongName       object
playerUrl      object
Nationality    object
Positions      object
                ...
PAS             int64
DRI             int64
DEF             int64
PHY             int64
Hits           object
Length: 77, dtype: object

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,...,Medium,Low,5 ★,85,92,91,95,38,65,\n372
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,...,High,Low,5 ★,89,93,81,89,35,77,\n344
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,...,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,...,High,High,4 ★,76,86,93,88,64,78,\n163
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,...,High,Medium,5 ★,91,85,86,94,36,59,\n273

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   photoUrl          18979 non-null  object
 1   LongName          18979 non-null  object
 2   playerUrl         18979 non-null  object
 3   Nationality       18979 non-null  object
 4   Positions         18979 non-null  object
 5   Name              18979 non-null  object
 6   Age               18979 non-null  int64
 7   ↓OVA              18979 non-null  int64
 8   POT               18979 non-null  int64
 9   Team & Contract   18979 non-null  object
 10  ID                18979 non-null  int64
 11  Height            18979 non-null  object
 12  Weight            18979 non-null  object
 13  foot              18979 non-null  object
 14  BOV               18979 non-null  int64
 15  BP                18979 non-null  object
 16  Growth            18979 non-null  int64
 17  Joined            18979 non-null  object
 18  Loan Date End     1013 non-null   object
 19  Value             18979 non-null  object
 20  Wage              18979 non-null  object
 21  Release Clause    18979 non-null  object
 22  Attacking         18979 non-null  int64
 23  Crossing          18979 non-null  int64
 24  Finishing         18979 non-null  int64
 25  Heading Accuracy  18979 non-null  int64
 26  Short Passing     18979 non-null  int64
 27  Volleys           18979 non-null  int64
 28  Skill             18979 non-null  int64
 29  Dribbling         18979 non-null  int64
 30  Curve             18979 non-null  int64
 31  FK Accuracy       18979 non-null  int64
 32  Long Passing      18979 non-null  int64
 33  Ball Control      18979 non-null  int64
 34  Movement          18979 non-null  int64
 35  Acceleration      18979 non-null  int64
 36  Sprint Speed      18979 non-null  int64
 37  Agility           18979 non-null  int64
 38  Reactions         18979 non-null  int64
 39  Balance           18979 non-null  int64
 40  Power             18979 non-null  int64
 41  Shot Power        18979 non-null  int64
 42  Jumping           18979 non-null  int64
 43  Stamina           18979 non-null  int64
 44  Strength          18979 non-null  int64
 45  Long Shots        18979 non-null  int64
 46  Mentality         18979 non-null  int64
 47  Aggression        18979 non-null  int64
 48  Interceptions     18979 non-null  int64
 49  Positioning       18979 non-null  int64
 50  Vision            18979 non-null  int64
 51  Penalties         18979 non-null  int64
 52  Composure         18979 non-null  int64
 53  Defending         18979 non-null  int64
 54  Marking           18979 non-null  int64
 55  Standing Tackle   18979 non-null  int64
 56  Sliding Tackle    18979 non-null  int64
 57  Goalkeeping       18979 non-null  int64
 58  GK Diving         18979 non-null  int64
 59  GK Handling       18979 non-null  int64
 60  GK Kicking        18979 non-null  int64
 61  GK Positioning    18979 non-null  int64
 62  GK Reflexes       18979 non-null  int64
 63  Total Stats       18979 non-null  int64
 64  Base Stats        18979 non-null  int64
 65  W/F               18979 non-null  object
 66  SM                18979 non-null  object
 67  A/W               18979 non-null  object
 68  D/W               18979 non-null  object
 69  IR                18979 non-null  object
 70  PAC               18979 non-null  int64
 71  SHO               18979 non-null  int64
 72  PAS               18979 non-null  int64
 73  DRI               18979 non-null  int64
 74  DEF               18979 non-null  int64
 75  PHY               18979 non-null  int64
 76  Hits              18979 non-null  object
dtypes: int64(55), object(22)
memory usage: 11.1+ MB

None

### Drop unnescessary rows/columns

In [4]:
fifa.drop(columns = ['photoUrl', 'playerUrl'], inplace = True)
fifa.rename(columns = {'LongName': 'Name'}, inplace = True)
fifa.rename(columns = {'↓OVA' : 'OVA'}, inplace = True)
fifa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 75 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              18979 non-null  object
 1   Nationality       18979 non-null  object
 2   Positions         18979 non-null  object
 3   Name              18979 non-null  object
 4   Age               18979 non-null  int64
 5   OVA               18979 non-null  int64
 6   POT               18979 non-null  int64
 7   Team & Contract   18979 non-null  object
 8   ID                18979 non-null  int64
 9   Height            18979 non-null  object
 10  Weight            18979 non-null  object
 11  foot              18979 non-null  object
 12  BOV               18979 non-null  int64
 13  BP                18979 non-null  object
 14  Growth            18979 non-null  int64
 15  Joined            18979 non-null  object
 16  Loan Date End     1013 non-null   object
 17  Value             18979 non-null  object
 18  Wage              18979 non-null  object
 19  Release Clause    18979 non-null  object
 20  Attacking         18979 non-null  int64
 21  Crossing          18979 non-null  int64
 22  Finishing         18979 non-null  int64
 23  Heading Accuracy  18979 non-null  int64
 24  Short Passing     18979 non-null  int64
 25  Volleys           18979 non-null  int64
 26  Skill             18979 non-null  int64
 27  Dribbling         18979 non-null  int64
 28  Curve             18979 non-null  int64
 29  FK Accuracy       18979 non-null  int64
 30  Long Passing      18979 non-null  int64
 31  Ball Control      18979 non-null  int64
 32  Movement          18979 non-null  int64
 33  Acceleration      18979 non-null  int64
 34  Sprint Speed      18979 non-null  int64
 35  Agility           18979 non-null  int64
 36  Reactions         18979 non-null  int64
 37  Balance           18979 non-null  int64
 38  Power             18979 non-null  int64
 39  Shot Power        18979 non-null  int64
 40  Jumping           18979 non-null  int64
 41  Stamina           18979 non-null  int64
 42  Strength          18979 non-null  int64
 43  Long Shots        18979 non-null  int64
 44  Mentality         18979 non-null  int64
 45  Aggression        18979 non-null  int64
 46  Interceptions     18979 non-null  int64
 47  Positioning       18979 non-null  int64
 48  Vision            18979 non-null  int64
 49  Penalties         18979 non-null  int64
 50  Composure         18979 non-null  int64
 51  Defending         18979 non-null  int64
 52  Marking           18979 non-null  int64
 53  Standing Tackle   18979 non-null  int64
 54  Sliding Tackle    18979 non-null  int64
 55  Goalkeeping       18979 non-null  int64
 56  GK Diving         18979 non-null  int64
 57  GK Handling       18979 non-null  int64
 58  GK Kicking        18979 non-null  int64
 59  GK Positioning    18979 non-null  int64
 60  GK Reflexes       18979 non-null  int64
 61  Total Stats       18979 non-null  int64
 62  Base Stats        18979 non-null  int64
 63  W/F               18979 non-null  object
 64  SM                18979 non-null  object
 65  A/W               18979 non-null  object
 66  D/W               18979 non-null  object
 67  IR                18979 non-null  object
 68  PAC               18979 non-null  int64
 69  SHO               18979 non-null  int64
 70  PAS               18979 non-null  int64
 71  DRI               18979 non-null  int64
 72  DEF               18979 non-null  int64
 73  PHY               18979 non-null  int64
 74  Hits              18979 non-null  object
dtypes: int64(55), object(20)
memory usage: 10.9+ MB

In [5]:
#Check for duplicates
fifa.duplicated().sum()

1

In [6]:
fifa.drop_duplicates(inplace = True)
fifa.duplicated().sum()

0

In [7]:
# Checking missing values
fifa.columns[fifa.isnull().any()]

Index(['Loan Date End'], dtype='object')

Because Loan Date End null value not cause by not recording but it doesn't exist so there will be no sense to try and guess the value it might be >> so we gonna keep it original

### Change index

In [8]:
fifa['ID'].is_unique

True

In [9]:
fifa = fifa.set_index('ID')
fifa.head()

,Name,Nationality,Positions,Name,Age,OVA,POT,Team & Contract,Height,Weight,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
ID,,,,,,,,,,,,,,,,,,,,,
158023,Lionel Messi,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,"5'7""",159lbs,...,Medium,Low,5 ★,85,92,91,95,38,65,\n372
20801,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,"6'2""",183lbs,...,High,Low,5 ★,89,93,81,89,35,77,\n344
200389,Jan Oblak,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,"6'2""",192lbs,...,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
192985,Kevin De Bruyne,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,"5'11""",154lbs,...,High,High,4 ★,76,86,93,88,64,78,\n163
190871,Neymar da Silva Santos Jr.,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,"5'9""",150lbs,...,High,Medium,5 ★,91,85,86,94,36,59,\n273

In [10]:
#Check all the columns
columns = list(fifa.columns)
pd.set_option('display.max_columns', 75)
display(fifa.head())

,Name,Nationality,Positions,Name,Age,OVA,POT,Team & Contract,Height,Weight,foot,BOV,BP,Growth,Joined,Loan Date End,Value,Wage,Release Clause,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
158023,Lionel Messi,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,"5'7""",159lbs,Left,93,RW,0,"Jul 1, 2004",NaN,€67.5M,€560K,€138.4M,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4 ★,4★,Medium,Low,5 ★,85,92,91,95,38,65,\n372
20801,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,"6'2""",183lbs,Right,92,ST,0,"Jul 10, 2018",NaN,€46M,€220K,€75.9M,437,84,95,90,82,86,414,88,81,76,77,92,431,87,91,87,95,71,444,94,95,84,78,93,353,63,29,95,82,84,95,84,28,32,24,58,7,11,15,14,11,2221,464,4 ★,5★,High,Low,5 ★,89,93,81,89,35,77,\n344
200389,Jan Oblak,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,"6'2""",192lbs,Right,91,GK,2,"Jul 16, 2014",NaN,€75M,€125K,€159.4M,95,13,11,15,43,13,109,12,13,14,40,30,307,43,60,67,88,49,268,59,78,41,78,12,140,34,19,11,65,11,68,57,27,12,18,437,87,92,78,90,90,1413,489,3 ★,1★,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
192985,Kevin De Bruyne,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,"5'11""",154lbs,Right,91,CAM,0,"Aug 30, 2015",NaN,€87M,€370K,€161M,407,94,82,55,94,82,441,88,85,83,93,92,398,77,76,78,91,76,408,91,63,89,74,91,408,76,66,88,94,84,91,186,68,65,53,56,15,13,5,10,13,2304,485,5 ★,4★,High,High,4 ★,76,86,93,88,64,78,\n163
190871,Neymar da Silva Santos Jr.,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,"5'9""",150lbs,Right,91,LW,0,"Aug 3, 2017",NaN,€90M,€270K,€166.5M,408,85,87,62,87,87,448,95,88,89,81,95,453,94,89,96,91,83,357,80,62,81,50,84,356,51,36,87,90,92,93,94,35,30,29,59,9,9,15,15,11,2175,451,5 ★,5★,High,Medium,5 ★,91,85,86,94,36,59,\n273

### Changing the data type
We can look through the previous columns info and see that some categories have the unuseful data type for analytic so we con the change it.
More specififcly, we will deal with 'Contract', 'Height', 'Weight', 'Joined', 'Value', 'Wage', 'Realease Clause', 'W/F', 'SM', 'IR', and 'Hits' columns.

#### Function to convert height and weight into numeric and cm/kg respectively

In [11]:
def hwConvert(x):
    if x.endswith('lbs') == True:
        x = x.replace('lbs', "")
        a = str(round(int(x)*0.45359237))
        return a
    elif x.endswith('kg') == True:
        x = x.replace('kg',"")
        return x
    elif x.endswith('cm') == True:
        x = x.replace('cm',"")
        return x
    else:
        x = x.replace("\'", " ").replace("\"", "").split()
        a = float(x[0])*30.48 + float(x[1])*2.54
        return str(round(a))

In [12]:
#Convert Weight
fifa['Weight'] = fifa['Weight'].map(hwConvert).astype(int)
#Rename & check
fifa.rename(columns = {'Weight':'Weight_kg'}, inplace=True)
fifa['Weight_kg']

ID
158023    72
20801     83
200389    87
192985    70
190871    68
          ..
257710    70
258736    58
247223    66
258760    65
255958    68
Name: Weight_kg, Length: 18978, dtype: int32

In [13]:
#Convert Height
fifa['Height'] = fifa['Height'].map(hwConvert).astype(int)
#Rename & check
fifa.rename(columns = {'Height':'Height_cm'}, inplace=True)
fifa['Height_cm']

ID
158023    170
20801     188
200389    188
192985    180
190871    175
         ...
257710    178
258736    170
247223    178
258760    175
255958    175
Name: Height_cm, Length: 18978, dtype: int32

In [14]:
# Formating 'Hits' and re-value Column
fifa['Hits'].unique()

array(['\n372', '\n344', '\n86', '\n163', '\n273', '\n182', '\n646',
       '\n79', '\n164', '\n170', '\n93', '\n131', '\n89', '\n90', '\n169',
       '\n187', '\n103', '\n317', '\n239', '\n56', '\n130', '\n229',
       '\n124', '\n172', '\n114', '\n46', '\n663', '\n479', '\n203',
       '\n198', '\n122', '\n565', '\n152', '\n140', '\n276', '\n209',
       '\n25', '\n136', '\n109', '\n139', '\n42', '\n99', '\n137',
       '\n166', '\n80', '\n104', '\n150', '\n112', '\n285', '\n133',
       '\n96', '\n69', '\n143', '\n100', '\n38', '\n83', '\n67', '\n207',
       '\n416', '\n315', '\n206', '\n424', '\n191', '\n454', '\n271',
       '\n249', '\n121', '\n246', '\n171', '\n148', '\n329', '\n70',
       '\n97', '\n73', '\n210', '\n82', '\n146', '\n62', '\n165', '\n129',
       '\n162', '\n35', '\n65', '\n47', '\n77', '\n106', '\n84', '\n1.3K',
       '\n310', '\n181', '\n364', '\n200', '\n141', '\n134', '\n259',
       '\n309', '\n367', '\n224', '\n211', '\n60', '\n176', '\n108',
       '\n63', '\n111', '\n52', '\n59', '\n350', '\n54', '\n117', '\n27',
       '\n91', '\n365', '\n312', '\n286', '\n157', '\n291', '\n245',
       '\n258', '\n233', '\n767', '\n288', '\n57', '\n115', '\n123',
       '\n142', '\n149', '\n227', '\n75', '\n53', '\n113', '\n71', '\n92',
       '\n144', '\n132', '\n125', '\n45', '\n158', '\n55', '\n43',
       '\n107', '\n24', '\n212', '\n21', '\n87', '\n39', '\n98', '\n192',
       '\n391', '\n23', '\n26', '\n13', '\n185', '\n177', '\n272',
       '\n193', '\n225', '\n78', '\n88', '\n37', '\n168', '\n85', '\n34',
       '\n1.5K', '\n48', '\n32', '\n215', '\n41', '\n20', '\n61', '\n68',
       '\n58', '\n19', '\n186', '\n17', '\n241', '\n574', '\n338',
       '\n274', '\n2.9K', '\n492', '\n670', '\n324', '\n352', '\n31',
       '\n30', '\n300', '\n189', '\n595', '\n127', '\n173', '\n159',
       '\n49', '\n36', '\n102', '\n280', '\n12', '\n14', '\n50', '\n76',
       '\n95', '\n51', '\n40', '\n22', '\n11', '\n9', '\n16', '\n10',
       '\n5', '\n222', '\n303', '\n268', '\n434', '\n256', '\n247',
       '\n248', '\n354', '\n289', '\n269', '\n237', '\n183', '\n6',
       '\n217', '\n155', '\n523', '\n921', '\n264', '\n72', '\n29',
       '\n476', '\n28', '\n205', '\n81', '\n393', '\n147', '\n74', '\n66',
       '\n33', '\n44', '\n314', '\n428', '\n261', '\n199', '\n281',
       '\n316', '\n118', '\n411', '\n396', '\n4', '\n794', '\n243',
       '\n204', '\n219', '\n167', '\n18', '\n356', '\n120', '\n561',
       '\n8', '\n101', '\n984', '\n2K', '\n603', '\n526', '\n1K', '\n343',
       '\n190', '\n154', '\n673', '\n194', '\n556', '\n128', '\n161',
       '\n494', '\n196', '\n232', '\n332', '\n283', '\n138', '\n15',
       '\n64', '\n94', '\n3', '\n7', '\n308', '\n382', '\n345', '\n275',
       '\n313', '\n398', '\n153', '\n935', '\n201', '\n699', '\n758',
       '\n745', '\n184', '\n1', '\n501', '\n145', '\n119', '\n255',
       '\n1.2K', '\n2', '\n253', '\n1.7K', '\n156', '\n238', '\n221',
       '\n175', '\n151', '\n500', '\n731', '\n532', '\n466', '\n535',
       '\n297', '\n265', '\n599', '\n234', '\n180', '\n195', '\n116',
       '\n423', '\n266', '\n560', '\n188', '\n244', '\n216', '\n496',
       '\n257', '\n226', '\n105', '\n412', '\n220', '\n970', '\n135',
       '\n360', '\n178', '\n1.1K', '\n326', '\n251', '\n369', '\n4.5K',
       '\n681', '\n700', '\n477', '\n333', '\n1.9K', '\n174', '\n406',
       '\n358', '\n555', '\n335', '\n856', '\n1.8K', '\n230', '\n250',
       '\n792', '\n400', '\n126', '\n342', '\n270', '\n529', '\n445',
       '\n830', '\n380', '\n881', '\n240', '\n160', '\n378', '\n598',
       '\n433', '\n202', 1, 2, 3, 16, 5, 208, 4, 11, 6, 19, 27, 8, 7, 13,
       10, 12, 9, 17, 21, 15, 20, 50, 18, 38, 43, 61, 49, 25, 22, 86, 14,
       26, 30, 60, 58], dtype=object)

In [15]:
fifa['Hits'] = fifa['Hits'].str.lstrip('\n').str.rstrip('\n').str.rstrip('K')
fifa['Hits'] = fifa['Hits'].fillna(value = '0')
fifa['Hits'] = fifa['Hits'].astype(float)
fifa['Hits']

ID
158023    372.0
20801     344.0
200389     86.0
192985    163.0
190871    273.0
          ...
257710      0.0
258736      0.0
247223      0.0
258760      0.0
255958      0.0
Name: Hits, Length: 18978, dtype: float64

In [16]:
# Stripping ★ symbol from 'W/F', 'SM', and 'IR' columns
fifa['W/F'] = fifa['W/F'].str.strip("★").astype(int)
fifa['SM'] = fifa['SM'].str.strip("★").astype(int)
fifa['IR'] = fifa['IR'].str.strip("★").astype(int)

#### Function to formatting the 'Wage', 'Value', 'Release Clause' columns

In [17]:
def value_setting(value): 
    if isinstance(value, str):
        if value.find("M") != -1:
            return int(float(value.replace("M", "").replace('€', '')) * 1000000)
        elif value.find("K") != -1: 
            return int(value.replace("K", "").replace("€", "")) * 1000 
    else:
        return int(value)

In [18]:
fifa['Value'] = fifa['Value'].apply(value_setting).fillna(value = 0)
fifa['Wage'] = fifa['Wage'].apply(value_setting).fillna(value = 0)
fifa['Release Clause'] = fifa['Release Clause'].apply(value_setting).fillna(value = 0)

## Rename & check
fifa.rename(columns = {'Value': 'Value_eur', 'Wage': 'Wage_eur', 'Release Clause': 'Release_Clause_eur'}, inplace = True)
fifa[['Value_eur', 'Wage_eur', 'Release_Clause_eur']]

         Value_eur  Wage_eur  Release_Clause_eur
ID
158023  67500000.0  560000.0         138400000.0
20801   46000000.0  220000.0          75900000.0
200389  75000000.0  125000.0         159400000.0
192985  87000000.0  370000.0         161000000.0
190871  90000000.0  270000.0         166500000.0
...            ...       ...                 ...
257710     35000.0    1000.0             57000.0
258736     60000.0       0.0            165000.0
247223     40000.0    1000.0             70000.0
258760     60000.0       0.0            165000.0
255958     60000.0       0.0            167000.0

[18978 rows x 3 columns]

In [19]:
# Formatting Team & Contract columns
fifa['Team & Contract'] = fifa['Team & Contract'].str.lstrip("\n").str.rstrip("\n")
fifa[['Team', 'Contract']] = fifa['Team & Contract'].str.split('\n', expand = True)
fifa['Contract'] = fifa['Contract'].str.replace("~", "-", regex = False)

# Drop old column & check
fifa = fifa.drop(columns = 'Team & Contract')
fifa[['Team', 'Contract']]

                                       Team     Contract
ID
158023                         FC Barcelona  2004 - 2021
20801                              Juventus  2018 - 2022
200389                      Atlético Madrid  2014 - 2023
192985                      Manchester City  2015 - 2023
190871                  Paris Saint-Germain  2017 - 2022
...                                     ...          ...
257710  Chongqing Dangdai Lifan FC SWM Team  2020 - 2020
258736                      Oldham Athletic  2020 - 2021
247223                           Wuhan Zall  2018 - 2022
258760                      Oldham Athletic  2020 - 2021
255958                         Club Bolívar  2020 - 2024

[18978 rows x 2 columns]

In [20]:
# Formatting 'Joined' to YYYY/MM/DD
fifa['Joined'] = pd.to_datetime(fifa['Joined'], yearfirst = True ,format = '%b %d, %Y')
#check
fifa['Joined']

ID
158023   2004-07-01
20801    2018-07-10
200389   2014-07-16
192985   2015-08-30
190871   2017-08-03
            ...
257710   2020-08-01
258736   2020-08-01
247223   2018-07-13
258760   2020-08-01
255958   2020-01-01
Name: Joined, Length: 18978, dtype: datetime64[ns]

In [21]:
fifa.head()

,Name,Nationality,Positions,Name,Age,OVA,POT,Height_cm,Weight_kg,foot,BOV,BP,Growth,Joined,Loan Date End,Value_eur,Wage_eur,Release_Clause_eur,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Team,Contract
ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
158023,Lionel Messi,Argentina,RW ST CF,L. Messi,33,93,93,170,72,Left,93,RW,0,2004-07-01,NaN,67500000.0,560000.0,138400000.0,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4,4,Medium,Low,5,85,92,91,95,38,65,372.0,FC Barcelona,2004 - 2021
20801,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,Cristiano Ronaldo,35,92,92,188,83,Right,92,ST,0,2018-07-10,NaN,46000000.0,220000.0,75900000.0,437,84,95,90,82,86,414,88,81,76,77,92,431,87,91,87,95,71,444,94,95,84,78,93,353,63,29,95,82,84,95,84,28,32,24,58,7,11,15,14,11,2221,464,4,5,High,Low,5,89,93,81,89,35,77,344.0,Juventus,2018 - 2022
200389,Jan Oblak,Slovenia,GK,J. Oblak,27,91,93,188,87,Right,91,GK,2,2014-07-16,NaN,75000000.0,125000.0,159400000.0,95,13,11,15,43,13,109,12,13,14,40,30,307,43,60,67,88,49,268,59,78,41,78,12,140,34,19,11,65,11,68,57,27,12,18,437,87,92,78,90,90,1413,489,3,1,Medium,Medium,3,87,92,78,90,52,90,86.0,Atlético Madrid,2014 - 2023
192985,Kevin De Bruyne,Belgium,CAM CM,K. De Bruyne,29,91,91,180,70,Right,91,CAM,0,2015-08-30,NaN,87000000.0,370000.0,161000000.0,407,94,82,55,94,82,441,88,85,83,93,92,398,77,76,78,91,76,408,91,63,89,74,91,408,76,66,88,94,84,91,186,68,65,53,56,15,13,5,10,13,2304,485,5,4,High,High,4,76,86,93,88,64,78,163.0,Manchester City,2015 - 2023
190871,Neymar da Silva Santos Jr.,Brazil,LW CAM,Neymar Jr,28,91,91,175,68,Right,91,LW,0,2017-08-03,NaN,90000000.0,270000.0,166500000.0,408,85,87,62,87,87,448,95,88,89,81,95,453,94,89,96,91,83,357,80,62,81,50,84,356,51,36,87,90,92,93,94,35,30,29,59,9,9,15,15,11,2175,451,5,5,High,Medium,5,91,85,86,94,36,59,273.0,Paris Saint-Germain,2017 - 2022

In [22]:
fifa.to_csv("cleaned_fifa21_data.csv", index=False)